### ISSUE TITLE
Timeframe?

### ISSUE THREAD

**Issue by losh11** [deginner/lamassu-dash-plugin#1]
I thought this entire thing would be completed in just one months. It's nearing the end of that month, and all we can see is a somewhat simple ticker!

Any idea when this'll be done?

**Comment by g-p-g** [comment]
The estimate was one to two months including some manual QA. It's still on track, just not visible on github yet.

**Comment by g-p-g** [comment]
https://github.com/deginner/DashLamassuProposal/wiki/Project was added to describe the different repos currently at github, although it's not fully in sync in terms of what's available in one's computer and what's here in github it's closer to completion.

This repository, lamassu-dash-plugin, is no longer intended to be used and, instead, the lamassu-dash repository contains the Lamassu plugins. Note that the plugins themselves are the simplest part for this project. It might be better to talk about these, if needed, outside github as it's not a good place for extended discussions unrelated to specific project issues.

**Comment by g-p-g** [comment]
This repository will be deleted in 2 days. https://github.com/deginner/lamassu-dash is the one that deals with Lamassu plugins for Dash.
